server:
  port: 4000
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:3000/eureka
  instance:
    instance-id: user-4000 #此实例注册到eureka服务端的唯一的实例ID

    #instance-id: ${spring.cloud.client.ip-address}/LQuan
    prefer-ip-address: true #是否显示IP地址
    leaseRenewalIntervalInSeconds: 10 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    leaseExpirationDurationInSeconds: 30 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒

spring:
  application:
    name: client-user #此实例注册到eureka服务端的name

#feign:
#  hystrix:
#    enabled: true

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 20000
#      circuitBreaker:
#        requestVolumeThreshold: 5
#        sleepWindowInMilliseconds : 5000   时间

#  threadpool:
#    default:
#      coreSize: 10

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'